export const availableAirports = [
  { key: "AAA", title: "AAA, Anaa, French Polynesia, PF" },
  { key: "AAB", title: "AAB, Arrabury, Queensland, Australia, AU" },
  { key: "AAC", title: "AAC, Al Arish, Egypt, EG" },
  { key: "AAD", title: "AAD, Adado, Somalia, SO" },
  { key: "AAE", title: "AAE, Annaba [El Mellah], Algeria, DZ" },
  { key: "AAF", title: "AAF, Apalachicola, FL [Apalachicola Municipal Airport]A, US" },
  { key: "AAG", title: "AAG, Arapoti Avelino Vieira, Brazil, BR" },
  { key: "AAH", title: "AAH, Aachen Merzbrueck, Germany, DE" },
  { key: "AAI", title: "AAI, Arraias, GO, Brazil, BR" },
  { key: "AAJ", title: "AAJ, Awaradam Cajana, Suriname, SR" },
  { key: "AAK", title: "AAK, Aranuka, Kiribati, KI" },
  { key: "AAL", title: "AAL, Aalborg, Denmark, DK" },
  { key: "AAM", title: "AAM, Mala Mala, South Africa, ZA" },
  { key: "AAN", title: "AAN, Al Ain, United Arab Emirates, AE" },
  { key: "AAO", title: "AAO, Anaco, Venezuela, VE" },
  { key: "AAP", title: "AAP, Houston Andrau Airpark, US" },
  { key: "AAQ", title: "AAQ, Anapa, Russia, RU" },
  { key: "AAR", title: "AAR, Aarhus [Tirstrup], Denmark, DK" },
  { key: "AAS", title: "AAS, Apalapsili, New Guinea, Indonesia, ID" },
  { key: "AAT", title: "AAT, Altay Air Base, CN" },
  { key: "AAU", title: "AAU, Asau, Western Samoa, WS" },
  { key: "AAV", title: "AAV, Alah, Philippines, PH" },
  { key: "AAX", title: "AAX, Araxa, MG, Brazil, BR" },
  { key: "AAY", title: "AAY, Al Ghaydah, Yemen, YE" },
  { key: "AAZ", title: "AAZ, Quezaltenango Airport, GT" },
  { key: "ABA", title: "ABA, Abakan, Khakassia, Russia, RU" },
  { key: "ABB", title: "ABB, Asaba International Airport Asaba, Nigeria , NG" },
  { key: "ABC", title: "ABC, Albacete Airport, Spain, ES" },
  { key: "ABD", title: "ABD, Abadan, Iran, IR" },
  { key: "ABE", title: "ABE, Allentown, PA [Allentown-Bethlehem-Easton Airport]A, US" },
  { key: "ABF", title: "ABF, Abaiang, Kiribati, KI" },
  { key: "ABG", title: "ABG, Abingoon, Queensland, Australia, AU" },
  { key: "ABH", title: "ABH, Alpha, Queensland, Australia, AU" },
  { key: "ABI", title: "ABI, Abilene, TX [Abilene Regional Airport]A, US" },
  { key: "ABJ", title: "ABJ, Abidjan [Felix Houphouet Boigny], Ivory Coast, CI" },
  { key: "ABK", title: "ABK, Kabri Dar, Ethiopia, ET" },
  { key: "ABL", title: "ABL, Ambler, AK [Ambler Airport]A, US" },
  { key: "ABM", title: "ABM, Cape York, Queensland [Bamaga], Australia, AU" },
  { key: "ABN", title: "ABN, Albina, Suriname, SR" },
  { key: "ABO", title: "ABO, Aboisso, Ivory Coast, CI" },
  { key: "ABP", title: "ABP, Atkamba, Papua New Guinea, PG" },
  { key: "ABQ", title: "ABQ, Albuquerque, NM [Albuquerque International Airport]A, US" },
  { key: "ABR", title: "ABR, Aberdeen, SD [Aberdeen Regional Airport]A, US" },
  { key: "ABS", title: "ABS, Abu Simbel, Egypt, EG" },
  { key: "ABT", title: "ABT, Al Baha Airport, SA" },
  { key: "ABU", title: "ABU, Atambua [Haliweni], Indonesia, ID" },
  { key: "ABV", title: "ABV, Abuja, Nigeria, NG" },
  { key: "ABW", title: "ABW, Abau, Papua New Guinea, PG" },
  { key: "ABX", title: "ABX, Albury, New South Wales, Australia, AU" },
  { key: "ABY", title: "ABY, Albany, GA [Southwest Georgia Regional Airport]A, US" },
  { key: "ABZ", title: "ABZ, Aberdeen, Scotland [Dyce], United Kingdom, GB" },
  { key: "ACA", title: "ACA, Acapulco [General Juan N. Alvarez], Mexico, MX" },
  { key: "ACB", title: "ACB, Bellaire, MI [Antrim County Airport]A, US" },
  { key: "ACC", title: "ACC, Accra [Kotoka], Ghana, GH" },
  { key: "ACD", title: "ACD, Acandi, Colombia, CO" },
  { key: "ACE", title: "ACE, Arrecife, Canary Islands [Lanzarote], Spain, ES" },
  { key: "ACH", title: "ACH, Altenrhein [Rorschach], Switzerland, CH" },
  { key: "ACI", title: "ACI, Alderney, Channel Islands, GB" },
  { key: "ACJ", title: "ACJ, Anuradhapura, Sri Lanka, LK" },
  { key: "ACK", title: "ACK, Nantucket, MA [Nantucket Memorial Airport]A, US" },
  { key: "ACL", title: "ACL, Aguaclara, Colombia, CO" },
  { key: "ACM", title: "ACM, Arica, Colombia, CO" },
  { key: "ACN", title: "ACN, Ciudad Acuna, Mexico, MX" },
  { key: "ACO", title: "ACO, Ascona, Switzerland, CH" },
  { key: "ACP", title: "ACP, Maragheh Sahand, Iran, IR" },
  { key: "ACR", title: "ACR, Araracuara, Colombia, CO" },
  { key: "ACS", title: "ACS, Anacortes, WA, USA, RU" },
  { key: "ACT", title: "ACT, Waco, TX [Waco Regional Airport]A, US" },
  { key: "ACU", title: "ACU, Achutupo, Panama, PA" },
  { key: "ACV", title: "ACV, Arcata/Eureka, CA [Arcata Airport]A, US" },
  { key: "ACX", title: "ACX, Xingyi, China, CN" },
  { key: "ACY", title: "ACY, Atlantic City, NJ [Atlantic City International Airport]A, US" },
  { key: "ACZ", title: "ACZ, Zabol, Iran, IR" },
  { key: "ADA", title: "ADA, Adana, Turkey, TR" },
  { key: "ADB", title: "ADB, Izmir [Adnan Menderes], Turkey, TR" },
  { key: "ADC", title: "ADC, Andakombe, Papua New Guinea, PG" },
  { key: "ADD", title: "ADD, Addis Ababa [Bole], Ethiopia, ET" },
  { key: "ADE", title: "ADE, Aden [International], Yemen, YE" },
  { key: "ADF", title: "ADF, Adıyaman Airport Adıyaman, Turkey , TR" },
  { key: "ADG", title: "ADG, Adrian, MI [Lenawee County Airport]A, US" },
  { key: "ADH", title: "ADH, Aldan, Yakutia-Sakha, Russia, RU" },
  { key: "ADI", title: "ADI, Arandis, Namibia, NA" },
  { key: "ADJ", title: "ADJ, Amman [Marka], Jordan, JO" },
  { key: "ADK", title: "ADK, Adak Island, AK [Adak Naval Air Station]A, US" },
  { key: "ADL", title: "ADL, Adelaide, South Australia [International], Australia, AU" },
  { key: "ADM", title: "ADM, Ardmore, OK [Ardmore Municipal Airport]A, US" },
  { key: "ADN", title: "ADN, Andes, Colombia, CO" },
  { key: "ADO", title: "ADO, Andamooka Airport, AU" },
  { key: "ADP", title: "ADP, Ampara Airport, LK" },
  { key: "ADQ", title: "ADQ, Kodiak, AK [Kodiak Airport]A, US" },
  { key: "ADR", title: "ADR, Andrews, SC [Andrews Municipal Airport]A, US" },
  { key: "ADS", title: "ADS, Dallas Addison Apt, United States of America, US" },
  { key: "ADT", title: "ADT, Ada, OK [Ada Municipal Airport]A, US" },
  { key: "ADU", title: "ADU, Ardabil, Iran, IR" },
  { key: "ADV", title: "ADV, El Daein Airport, SD" },
  { key: "ADW", title: "ADW, Camp Springs, MD [Andrews Air Force Base]A, US" },
  { key: "ADX", title: "ADX, St. Andrews, Scotland, United Kingdom, GB" },
  { key: "ADY", title: "ADY, Alldays, South Africa, ZA" },
  { key: "ADZ", title: "ADZ, San Andres Island, San Andres [Sesquicentenario], Colombia, CO" },
  { key: "AEA", title: "AEA, Abemama Atoll, Kiribati, KI" },
  { key: "AEB", title: "AEB, Baise Youjiang, China, CN" },
  { key: "AED", title: "AED, Aleneva, United States of America, US" },
  { key: "AEE", title: "AEE, Adareil, SS" },
  { key: "AEG", title: "AEG, Aek Godang, Indonesia, ID" },
  { key: "AEH", title: "AEH, Abeche, Chad, TD" },
  { key: "AEJ", title: "AEJ, Ahmed Al Jaber, Kuwait, KW" },
  { key: "AEK", title: "AEK, Aseki, Papua New Guinea, PG" },
  { key: "AEL", title: "AEL, Albert Lea, MN [Albert Lea Municipal Airport]A, US" },
  { key: "AEM", title: "AEM, Amgu, Russian Federation, RU" },
  { key: "AEO", title: "AEO, Aioun el Atrouss, Mauritania, MR" },
  { key: "AEP", title: "AEP, Buenos Aires [Aeroparque Jorge Newbery], Argentina, AR" },
  { key: "AER", title: "AER, Adler/Sochi, Krasnodar, Russia, RU" },
  { key: "AES", title: "AES, Alesund (Aalesund) [Vigra], Norway, NO" },
  { key: "AET", title: "AET, Allakaket, AK [Allakaket Airport]A, US" },
  { key: "AEU", title: "AEU, Abu Musa Island, Iran, IR" },
  { key: "AEX", title: "AEX, Alexandria International Airport, US" },
  { key: "AEY", title: "AEY, Akureyri, Iceland, IS" },
  { key: "AFA", title: "AFA, San Rafael, Argentina, AR" },
  { key: "AFD", title: "AFD, Port Alfred, South Africa, ZA" },
  { key: "AFF", title: "AFF, Colorado Springs Usaf Academy Airfield, United States of America, US" },
  { key: "AFI", title: "AFI, Amalfi, Colombia, CO" },
  { key: "AFK", title: "AFK, Ampara Kondavattavan Tank Spb, Sri Lanka, LK" },
  { key: "AFL", title: "AFL, Alta Floresta, Brazil, BR" },
  { key: "AFN", title: "AFN, Jaffrey Silver Ranch, United States of America, US" },
  { key: "AFO", title: "AFO, Afton, WY [Afton Municipal Airport]A, US" },
  { key: "AFR", title: "AFR, Afore, Papua New Guinea, PG" },
  { key: "AFS", title: "AFS, Zarafshan, Uzbekistan, UZ" },
  { key: "AFT", title: "AFT, Afutara, Solomon Islands, SB" },
  { key: "AFU", title: "AFU, Al Udeid, Qatar, QA" },
  { key: "AFW", title: "AFW, Fort Worth Alliance, United States of America, US" },
  { key: "AFY", title: "AFY, Afyon, Turkey, TR" },
  { key: "AFZ", title: "AFZ, Sabzevar, Iran, IR" },
  { key: "AGA", title: "AGA, Agadir [Al Massira], Morocco, MA" },
  { key: "AGB", title: "AGB, Augsburg, Germany, DE" },
  { key: "AGC", title: "AGC, Pittsburgh, PA [Allegheny County Airport]A, US" },
  { key: "AGD", title: "AGD, Anggi, Indonesia, ID" },
  { key: "AGE", title: "AGE, Wangerooge, Germany, DE" },
  { key: "AGF", title: "AGF, Agen, France, FR" },
  { key: "AGG", title: "AGG, Angoram, Papua New Guinea, PG" },
  { key: "AGH", title: "AGH, Angelholm (Helsingborg), Sweden, SE" },
  { key: "AGI", title: "AGI, Wageningen, Suriname, SR" },
  { key: "AGJ", title: "AGJ, Aguni, Japan, JP" },
  { key: "AGK", title: "AGK, Kagua, Papua New Guinea, PG" },
  { key: "AGL", title: "AGL, Wanigela, Papua New Guinea, PG" },
  { key: "AGM", title: "AGM, Anqmaqssalik, Greenland, GL" },
  { key: "AGN", title: "AGN, Angoon, AK [Angoon Seaplane Base]A, US" },
  { key: "AGO", title: "AGO, Magnolia, AR [Magnolia Municipal Airport]A, US" },
  { key: "AGP", title: "AGP, Malaga [Pablo Ruiz Picasso], Spain, ES" },
  { key: "AGQ", title: "AGQ, Agrinion, Greece, GR" },
  { key: "AGR", title: "AGR, Agra, India, IN" },
  { key: "AGS", title: "AGS, Augusta, GA [Bush Field]A, US" },
  { key: "AGT", title: "AGT, Ciudad del Este, Paraguay, PY" },
  { key: "AGU", title: "AGU, Aguascalientes, Mexico, MX" },
  { key: "AGV", title: "AGV, Acarigua, Venezuela, VE" },
  { key: "AGW", title: "AGW, Agnew, Queensland, Australia, AU" },
  { key: "AGX", title: "AGX, Agatti Island, India, IN" },
  { key: "AGY", title: "AGY, Argyle Downs, Western Australia, Australia, AU" },
  { key: "AGZ", title: "AGZ, Aggeneys, South Africa, ZA" },
  { key: "AHA", title: "AHA, Naha, Okinawa [Naha Air Force Base], Japan, JP" },
  { key: "AHB", title: "AHB, Khamis Mushayat (Abha), Saudi Arabia, SA" },
  { key: "AHC", title: "AHC, Herlong Amedee Army Air Field, United States of America, US" },
  { key: "AHD", title: "AHD, Ardmore Downtown Executive Apt, United States of America, US" },
  { key: "AHE", title: "AHE, Ahe, French Polynesia, PF" },
  { key: "AHF", title: "AHF, Arapahoe, United States of America, US" },
  { key: "AHH", title: "AHH, Amery, WI [Amery Municipal Airport]A, US" },
  { key: "AHI", title: "AHI, Amahai, Indonesia, ID" },
  { key: "AHJ", title: "AHJ,  Hongyuan [Ngawa], China, CN" },
  { key: "AHL", title: "AHL, Aishalton, Guyana, GY" },
  { key: "AHM", title: "AHM, Ashland Municipal, United States of America, US" },
  { key: "AHN", title: "AHN, Athens, GA [Athens/Ben Epps Airport]A, US" },
  { key: "AHO", title: "AHO, Alghero, Sardinia [Fertilia], Italy, IT" },
  { key: "AHS", title: "AHS, Ahuas, Honduras, HN" },
  { key: "AHT", title: "AHT, Amchitka, AK [Amchitka Island Airport]A, US" },
  { key: "AHU", title: "AHU, Al Hoceima [Cote du Rif], Morocco, MA" },
  { key: "AHW", title: "AHW, Saih Rawl, Oman, OM" },
  { key: "AHY", title: "AHY, Ambatolahy, Madagascar, MG" },
  { key: "AHZ", title: "AHZ, Alpe d'Huez, France, FR" },
  { key: "AIA", title: "AIA, Alliance, NE [Alliance Municipal Airport]A, US" },
  { key: "AIB", title: "AIB, Anita Bay, AKA, US" },
  { key: "AIC", title: "AIC, Ailinglaplap Airok Airport, MH" },
  { key: "AID", title: "AID, Anderson Municipal, United States of America, US" },
  { key: "AIE", title: "AIE, Aiome, Papua New Guinea, PG" },
  { key: "AIF", title: "AIF, Assis, SP, Brazil, BR" },
  { key: "AIG", title: "AIG, Yalinga, Central African Republic, CF" },
  { key: "AIH", title: "AIH, Aiambak, Papua New Guinea, PG" },
  { key: "AII", title: "AII, Ali Sabieh, Djibouti, DJ" },
  { key: "AIK", title: "AIK, Aiken, SC [Aiken Municipal Airport]A, US" },
  { key: "AIL", title: "AIL, Ailigandi, Panama, PA" },
  { key: "AIM", title: "AIM, Ailuk, Ine Island, Marshall Islands, MH" },
  { key: "AIN", title: "AIN, Wainwright, AK [Wainwright Airport]A, US" },
  { key: "AIO", title: "AIO, Atlantic, IA [Atlantic Municipal Airport]A, US" },
  { key: "AIP", title: "AIP, Adampur, India, IN" },
  { key: "AIR", title: "AIR, Aripuana, MT, Brazil, BR" },
  { key: "AIS", title: "AIS, Arorae Island, Kiribati, KI" },
  { key: "AIT", title: "AIT, Aitutaki, Cook Islands, CK" },
  { key: "AIU", title: "AIU, Atiu, Cook Islands, CK" },
  { key: "AIV", title: "AIV, Aliceville, AL [George Downer Airport]A, US" },
  { key: "AIW", title: "AIW, Ai-Ais, Namibia, NA" },
  { key: "AIY", title: "AIY, Atlantic City, NJ [Atlantic City Municipal Airport]A, US" },
  { key: "AIZ", title: "AIZ, Kaiser/Lake Ozark, MO [Lee C. Fine Memorial Airport]A, US" },
  { key: "AJA", title: "AJA, Ajaccio, Corsica [Campo Dell'Oro], France, FR" },
  { key: "AJF", title: "AJF, Jouf, Saudi Arabia, SA" },
  { key: "AJI", title: "AJI, Agri, Turkey, TR" },
  { key: "AJJ", title: "AJJ, Akjoujt, Mauritania, MR" },
  { key: "AJK", title: "AJK, Araak, Iran, IR" },
  { key: "AJL", title: "AJL, Aizawl, India, IN" },
  { key: "AJN", title: "AJN, Anjouan, Comoros, KM" },
  { key: "AJO", title: "AJO, Aljouf, Yemen, YE" },
  { key: "AJR", title: "AJR, Arvidsjaur, Sweden, SE" },
  { key: "AJS", title: "AJS, Abreojos, Mexico, MX" },
  { key: "AJU", title: "AJU, Aracaju, SE, Brazil, BR" },
  { key: "AJY", title: "AJY, Agades (Agadez), Niger, NE" },
  { key: "AKA", title: "AKA, Ankang, China, CN" },
  { key: "AKB", title: "AKB, Atka, AK [Atka Airport]A, US" },
  { key: "AKC", title: "AKC, Akron/Canton Akron Fulton Intl, United States of America, US" },
  { key: "AKD", title: "AKD, Akola, India, IN" },
  { key: "AKE", title: "AKE, Akieni, Gabon, GA" },
  { key: "AKF", title: "AKF, Kufrah, Libya, LY" },
  { key: "AKG", title: "AKG, Anguganak, Papua New Guinea, PG" },
  { key: "AKH", title: "AKH, Al Kharj Prince Sultan Air Base, Saudi Arabia, SA" },
  { key: "AKI", title: "AKI, Akiak, AK [Akiak Airport]A, US" },
  { key: "AKJ", title: "AKJ, Asahikawa, Japan, JP" },
  { key: "AKK", title: "AKK, Akhiok, AK [Akhiok Airport]A, US" },
  { key: "AKL", title: "AKL, Auckland [International], New Zealand, NZ" },
  { key: "AKM", title: "AKM, Zakouma, Chad, TD" },
  { key: "AKN", title: "AKN, King Salmon, AK [King Salmon Airport]A, US" },
  { key: "AKO", title: "AKO, Akron, CO [Akron-Washington County Airport]A, US" },
  { key: "AKP", title: "AKP, Anaktuvuk Pass, AK [Anaktuvuk Pass Airport]A, US" },
  { key: "AKQ", title: "AKQ, Astraksetra, Indonesia, ID" },
  { key: "AKR", title: "AKR, Akure, Nigeria, NG" },
  { key: "AKS", title: "AKS, Auki, Solomon Islands, SB" },
  { key: "AKT", title: "AKT, Akrotiri Royal Air Force, Cyprus, CY" },
  { key: "AKU", title: "AKU, Aksu Airport, CN" },
  { key: "AKV", title: "AKV, Akulivik, QC, Canada, CA" },
  { key: "AKW", title: "AKW, Aghajari, Iran, IR" },
  { key: "AKX", title: "AKX, Aqtobe (Aktyubinsk), Aqtobe, Kazakhstan, KZ" },
  { key: "AKY", title: "AKY, Sittwe (Akyab), Myanmar, MM" },
  { key: "ALA", title: "ALA, Almaty (Alma Ata), Alma Ata, Kazakhstan, KZ" },
  { key: "ALB", title: "ALB, Albany, NY [Albany County Airport]A, US" },
  { key: "ALC", title: "ALC, Alicante, Spain, ES" },
  { key: "ALD", title: "ALD, Alerta, Peru, PE" },
  { key: "ALE", title: "ALE, Alpine, TX [Alpine-Casparis Municipal Airport]A, US" },
  { key: "ALF", title: "ALF, Alta, Norway, NO" },
  { key: "ALG", title: "ALG, Alger (Algiers) [Houari Boumediene], Algeria, DZ" },
  { key: "ALH", title: "ALH, Albany, Western Australia, Australia, AU" },
  { key: "ALI", title: "ALI, Alice, TX [Alice International Airport]A, US" },
  { key: "ALJ", title: "ALJ, Alexander Bay, South Africa, ZA" },
  { key: "ALK", title: "ALK, Asela, Ethiopia, ET" },
  { key: "ALL", title: "ALL, Albenga, Italy, IT" },
  { key: "ALM", title: "ALM, Alamogordo, NM [Alamogordo-White Sands Regional Airport]A, US" },
  { key: "ALN", title: "ALN, Alton, IL/St. Louis, MO [St. Louis Regional Airport]A, US" },
  { key: "ALO", title: "ALO, Waterloo, IA [Waterloo Municipal Airport]A, US" }
];
